### ISSUE TITLE
[Suggestion] This will be a good add-on, Bezier Shadow

### ISSUE THREAD

**Issue by Paget96** [AppDevNext/AndroidChart#179]
Please check this out!

![68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f32303139303530363039353431303632362e706e673f782d6f73732d70726f636573733d696d6167652f77617465726d61726b2c747970655f5a6d46755a33706f5a57356e6147567064476b2c7368](https://github.com/AppDevNext/AndroidChart/assets/10515077/5dbd6b78-9658-4ace-a32e-cf82de9186bc)

Link:
https://github.com/stramChen/MPAndroidChart-Bezier-shadow

**Comment by hannesa2** [comment]
Sure.
*  They have not the same git commit base
* I did a rebase of their master to this master. 
* They have just new files. Because some of them were converted by me to Kotlin. 
<img width="1051" alt="image" src="https://github.com/AppDevNext/AndroidChart/assets/3314607/0d2db455-6afb-41cc-b367-099a16c21241">

I see no base from where I can investigate and apply changes here.  

If you can make a pull request, I will merge it

**Comment by hannesa2** [comment]
Look at there commit list https://github.com/stramChen/MPAndroidChart-Bezier-shadow/commits/master. Looks like just one commit, which rules it all. There is no breaking change commit.

**Comment by Paget96** [comment]
> Look at there commit list https://github.com/stramChen/MPAndroidChart-Bezier-shadow/commits/master. Looks like just one commit, which rules it all. There is no breaking change commit.

I do agree, I'll take a look at free time.
